import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter3/main.dart';

void main() {
  runApp(MyApp());
}

class Autogenerated {
  int? id;
  int? userid;
  String? title;
  String? body;

  Autogenerated({this.id, this.userid, this.title, this.body});
  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userid = json['userid'];
    title = json['title'];
    body = json['body'];
  }
}

class dioo extends StatefulWidget {
  const dioo({super.key});

  @override
  State<dioo> createState() => _diooState();
}

class _diooState extends State<dioo> {
  final Dio dio = Dio();
  List<Autogenerated> see = [];

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    fetching();
  }

  Future<void> fetching() async {
    try {
      final response = await dio.get('https://gorest.co.in/public/v2/posts');
      if (response.statusCode == 200) {
        final List<dynamic> data = response.data;
        print('data ,${response.data}');

        setState(() {
          see.clear();
          see.addAll(data.map((postJson) => Autogenerated.fromJson(postJson)));
        });
      } else {
        print('failed to load post');
      }
    } catch (e) {
      print('error:$e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('see'),
        ),
        body: ListView.builder(
          itemCount: see.length,
          itemBuilder: (context, index) {
            return ListTile(
              title: Text(see[index].title!),
              subtitle:Text(see[index].body!),
            );
          },
        ),
      ),
    );
  }
}
